#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
CONFIG_PATH="$CONFIG_DIR/provider.env"
NEXT_CMD="bash runs/run_sequential.sh inputs/probe.txt"
SELECTED_PROVIDER_TYPE=""
SELECTED_PROVIDER_NAME=""
NON_INTERACTIVE="0"
RUN_PROBE_AFTER_SETUP="ask"
OUTPUT_MODE="file"
PROVIDER_ARG=""
API_KEY_ARG=""
MODEL_ARG=""
BASE_URL_ARG=""
AGENT_BIN_ARG=""
OLLAMA_BASE_URL_ARG=""
CONFIG_PATH_ARG=""

emit_config() {
  if [ "$OUTPUT_MODE" = "stdout" ]; then
    cat
  else
    cat > "$CONFIG_PATH"
  fi
}

usage() {
  cat <<'EOF'
用法:
  bash runs/setup_provider.sh
  bash runs/setup_provider.sh --non-interactive --provider deepseek --api-key YOUR_KEY --model YOUR_MODEL

参数:
  --non-interactive        使用非交互模式生成 config/provider.env
  --provider NAME          provider 名称，可选:
                           openrouter, deepseek, moonshot, siliconflow, groq,
                           custom, ollama, openclaw
  --api-key VALUE          OpenAI-compatible provider 使用的 API key
  --model VALUE            OpenAI-compatible provider 或 Ollama 使用的模型名
  --base-url VALUE         custom provider 或覆盖默认接口地址
  --ollama-base-url VALUE  覆盖 Ollama 默认地址
  --agent-bin PATH         OpenClaw 可执行文件路径
  --config PATH            输出配置文件路径，默认 config/provider.env
  --run-probe              生成配置后立即运行 probe 测试
  --no-run-probe           生成配置后不运行 probe 测试
  --stdout                 将生成的配置打印到 stdout，不写入文件
  -h, --help               显示本帮助
EOF
}

parse_args() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --non-interactive)
        NON_INTERACTIVE="1"
        shift
        ;;
      --provider)
        [ "$#" -ge 2 ] || { echo "错误：--provider 需要一个参数" >&2; exit 1; }
        PROVIDER_ARG="$2"
        shift 2
        ;;
      --api-key)
        [ "$#" -ge 2 ] || { echo "错误：--api-key 需要一个参数" >&2; exit 1; }
        API_KEY_ARG="$2"
        shift 2
        ;;
      --model)
        [ "$#" -ge 2 ] || { echo "错误：--model 需要一个参数" >&2; exit 1; }
        MODEL_ARG="$2"
        shift 2
        ;;
      --base-url)
        [ "$#" -ge 2 ] || { echo "错误：--base-url 需要一个参数" >&2; exit 1; }
        BASE_URL_ARG="$2"
        shift 2
        ;;
      --ollama-base-url)
        [ "$#" -ge 2 ] || { echo "错误：--ollama-base-url 需要一个参数" >&2; exit 1; }
        OLLAMA_BASE_URL_ARG="$2"
        shift 2
        ;;
      --agent-bin)
        [ "$#" -ge 2 ] || { echo "错误：--agent-bin 需要一个参数" >&2; exit 1; }
        AGENT_BIN_ARG="$2"
        shift 2
        ;;
      --config)
        [ "$#" -ge 2 ] || { echo "错误：--config 需要一个参数" >&2; exit 1; }
        CONFIG_PATH_ARG="$2"
        shift 2
        ;;
      --run-probe)
        RUN_PROBE_AFTER_SETUP="y"
        shift
        ;;
      --no-run-probe)
        RUN_PROBE_AFTER_SETUP="n"
        shift
        ;;
      --stdout)
        OUTPUT_MODE="stdout"
        RUN_PROBE_AFTER_SETUP="n"
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "错误：未知参数 $1" >&2
        usage >&2
        exit 1
        ;;
    esac
  done
}

parse_args "$@"

if [ -n "$CONFIG_PATH_ARG" ]; then
  CONFIG_PATH="$CONFIG_PATH_ARG"
  CONFIG_DIR="$(cd "$(dirname "$CONFIG_PATH")" && pwd)"
fi

mkdir -p "$CONFIG_DIR"

if [ "$OUTPUT_MODE" != "stdout" ] && [ -f "$CONFIG_PATH" ]; then
  echo "提示：将覆盖已有配置文件 $CONFIG_PATH"
  echo
fi

prompt_required() {
  local label="$1"
  local value=""
  while [ -z "$value" ]; do
    printf "%s: " "$label" >&2
    IFS= read -r value
    if [ -z "$value" ]; then
      echo "该项不能为空，请再输入一次。" >&2
    fi
  done
  printf '%s' "$value"
}

prompt_optional() {
  local label="$1"
  local default_value="${2:-}"
  local value=""
  if [ -n "$default_value" ]; then
    printf "%s [%s]: " "$label" "$default_value" >&2
  else
    printf "%s: " "$label" >&2
  fi
  IFS= read -r value
  if [ -z "$value" ]; then
    value="$default_value"
  fi
  printf '%s' "$value"
}

write_openai_compatible_config() {
  local provider_name="$1"
  local key_label="$2"
  local key model base_url
  SELECTED_PROVIDER_TYPE="openai_compatible"
  SELECTED_PROVIDER_NAME="$provider_name"

  key="$(prompt_required "$key_label")"
  model="$(prompt_required "模型名 HWP_LLM_MODEL")"

  case "$provider_name" in
    custom)
      base_url="$(prompt_required "Base URL HWP_LLM_BASE_URL")"
      ;;
    *)
      base_url="$(prompt_optional "自定义 Base URL（留空则使用内置默认值）")"
      ;;
  esac

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=openai_compatible"
    echo "HWP_PROVIDER_NAME=$provider_name"
    echo "HWP_LLM_API_KEY=$key"
    echo "HWP_LLM_MODEL=$model"
    if [ -n "$base_url" ]; then
      echo "HWP_LLM_BASE_URL=$base_url"
    fi
  } | emit_config
}

write_ollama_config() {
  local model base_url
  SELECTED_PROVIDER_TYPE="ollama"
  SELECTED_PROVIDER_NAME="ollama"
  model="$(prompt_required "本地模型名 OLLAMA_MODEL")"
  base_url="$(prompt_optional "Ollama Base URL" "http://127.0.0.1:11434")"

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=ollama"
    echo "HWP_PROVIDER_NAME=ollama"
    echo "OLLAMA_MODEL=$model"
    if [ -n "$base_url" ]; then
      echo "OLLAMA_BASE_URL=$base_url"
    fi
  } | emit_config
}

write_openclaw_config() {
  local agent_bin
  SELECTED_PROVIDER_TYPE="openclaw"
  SELECTED_PROVIDER_NAME="openclaw"
  agent_bin="$(prompt_optional "OpenClaw 可执行文件路径（留空则使用 PATH 中的 openclaw）")"

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=openclaw"
    echo "HWP_PROVIDER_NAME=openclaw"
    if [ -n "$agent_bin" ]; then
      echo "HWP_AGENT_BIN=$agent_bin"
    fi
  } | emit_config
}

print_next_steps() {
  if [ "$OUTPUT_MODE" = "stdout" ]; then
    return 0
  fi
  echo
  echo "已生成配置文件：$CONFIG_PATH"
  echo "当前 provider: ${SELECTED_PROVIDER_TYPE:-unknown}/${SELECTED_PROVIDER_NAME:-unknown}"
  echo
  case "$SELECTED_PROVIDER_TYPE" in
    openai_compatible)
      echo "建议检查："
      echo "- config/provider.env 中的 HWP_LLM_API_KEY 是否已填入真实 key"
      echo "- config/provider.env 中的 HWP_LLM_MODEL 是否与平台支持的模型名一致"
      if [ "${SELECTED_PROVIDER_NAME:-}" = "custom" ]; then
        echo "- config/provider.env 中的 HWP_LLM_BASE_URL 是否为正确的兼容接口地址"
      else
        echo "- 如需覆盖默认接口地址，可手动补充 HWP_LLM_BASE_URL"
      fi
      ;;
    ollama)
      echo "建议检查："
      echo "- 本地 Ollama 服务是否已启动"
      echo "- config/provider.env 中的 OLLAMA_MODEL 是否已在本地拉取"
      echo "- 如需自定义地址，可修改 OLLAMA_BASE_URL"
      ;;
    openclaw)
      echo "建议检查："
      echo "- openclaw 是否已安装并可在终端中直接运行"
      echo "- 如果不在 PATH 中，可在 config/provider.env 中补 HWP_AGENT_BIN"
      ;;
  esac
  echo
  echo "下一步可直接运行："
  echo "$NEXT_CMD"
  echo
  echo "如果想先确认配置内容："
  echo "sed -n '1,40p' config/provider.env"
}

prompt_yes_no() {
  local label="$1"
  local default_value="${2:-n}"
  local hint="y/N"
  local answer=""

  if [ "$default_value" = "y" ]; then
    hint="Y/n"
  fi

  printf "%s [%s]: " "$label" "$hint" >&2
  IFS= read -r answer
  answer="$(printf '%s' "$answer" | tr '[:upper:]' '[:lower:]')"

  if [ -z "$answer" ]; then
    answer="$default_value"
  fi

  case "$answer" in
    y|yes) return 0 ;;
    n|no) return 1 ;;
    *)
      echo "未识别输入，按“否”处理。" >&2
      return 1
      ;;
  esac
}

require_non_empty_arg() {
  local value="$1"
  local label="$2"
  if [ -z "$value" ]; then
    echo "错误：非交互模式下必须提供 $label" >&2
    exit 1
  fi
}

write_openai_compatible_config_non_interactive() {
  local provider_name="$1"
  SELECTED_PROVIDER_TYPE="openai_compatible"
  SELECTED_PROVIDER_NAME="$provider_name"
  require_non_empty_arg "$API_KEY_ARG" "--api-key"
  require_non_empty_arg "$MODEL_ARG" "--model"
  if [ "$provider_name" = "custom" ]; then
    require_non_empty_arg "$BASE_URL_ARG" "--base-url"
  fi

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=openai_compatible"
    echo "HWP_PROVIDER_NAME=$provider_name"
    echo "HWP_LLM_API_KEY=$API_KEY_ARG"
    echo "HWP_LLM_MODEL=$MODEL_ARG"
    if [ -n "$BASE_URL_ARG" ]; then
      echo "HWP_LLM_BASE_URL=$BASE_URL_ARG"
    fi
  } | emit_config
}

write_ollama_config_non_interactive() {
  SELECTED_PROVIDER_TYPE="ollama"
  SELECTED_PROVIDER_NAME="ollama"
  require_non_empty_arg "$MODEL_ARG" "--model"

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=ollama"
    echo "HWP_PROVIDER_NAME=ollama"
    echo "OLLAMA_MODEL=$MODEL_ARG"
    if [ -n "$OLLAMA_BASE_URL_ARG" ]; then
      echo "OLLAMA_BASE_URL=$OLLAMA_BASE_URL_ARG"
    fi
  } | emit_config
}

write_openclaw_config_non_interactive() {
  SELECTED_PROVIDER_TYPE="openclaw"
  SELECTED_PROVIDER_NAME="openclaw"

  {
    echo "# Generated by runs/setup_provider.sh"
    echo "HWP_PROVIDER_TYPE=openclaw"
    echo "HWP_PROVIDER_NAME=openclaw"
    if [ -n "$AGENT_BIN_ARG" ]; then
      echo "HWP_AGENT_BIN=$AGENT_BIN_ARG"
    fi
  } | emit_config
}

run_non_interactive_setup() {
  local provider
  provider="$(printf '%s' "$PROVIDER_ARG" | tr '[:upper:]' '[:lower:]')"
  require_non_empty_arg "$provider" "--provider"

  case "$provider" in
    openrouter|deepseek|moonshot|siliconflow|groq|custom)
      write_openai_compatible_config_non_interactive "$provider"
      ;;
    ollama)
      write_ollama_config_non_interactive
      ;;
    openclaw)
      write_openclaw_config_non_interactive
      ;;
    *)
      echo "错误：不支持的 --provider 值: $provider" >&2
      echo "支持：openrouter, deepseek, moonshot, siliconflow, groq, custom, ollama, openclaw" >&2
      exit 1
      ;;
  esac
}

run_probe_test() {
  if [ "$OUTPUT_MODE" = "stdout" ]; then
    echo "错误：--stdout 模式下不能运行 probe 测试" >&2
    return 1
  fi
  echo
  echo "开始运行 probe 测试："
  echo "$NEXT_CMD"
  echo
  if (cd "$ROOT_DIR" && bash runs/run_sequential.sh inputs/probe.txt); then
    echo
    echo "probe 测试已完成。"
  else
    echo
    echo "probe 测试运行失败。"
    echo "建议先检查："
    echo "- config/provider.env 中的 provider 配置是否正确"
    echo "- 所选 provider 对应的服务、API key、模型名是否可用"
    echo "- logs/run.log 中是否有更具体的错误信息"
    return 1
  fi
}

if [ "$NON_INTERACTIVE" = "1" ]; then
  run_non_interactive_setup
else
  echo "选择你的 provider："
  echo "1. OpenRouter"
  echo "2. DeepSeek"
  echo "3. Moonshot / Kimi"
  echo "4. SiliconFlow"
  echo "5. Groq"
  echo "6. 其他兼容 OpenAI API 的平台"
  echo "7. Ollama"
  echo "8. OpenClaw"
  printf "请输入编号 [1-8]: "
  IFS= read -r provider_choice

  case "$provider_choice" in
    1) write_openai_compatible_config "openrouter" "OpenRouter API Key HWP_LLM_API_KEY" ;;
    2) write_openai_compatible_config "deepseek" "DeepSeek API Key HWP_LLM_API_KEY" ;;
    3) write_openai_compatible_config "moonshot" "Moonshot API Key HWP_LLM_API_KEY" ;;
    4) write_openai_compatible_config "siliconflow" "SiliconFlow API Key HWP_LLM_API_KEY" ;;
    5) write_openai_compatible_config "groq" "Groq API Key HWP_LLM_API_KEY" ;;
    6) write_openai_compatible_config "custom" "API Key HWP_LLM_API_KEY" ;;
    7) write_ollama_config ;;
    8) write_openclaw_config ;;
    *)
      echo "错误：无效编号 $provider_choice"
      exit 1
      ;;
  esac
fi

echo
print_next_steps

if [ "$RUN_PROBE_AFTER_SETUP" = "ask" ]; then
  if prompt_yes_no "是否立即运行一次 probe 测试？" "n"; then
    run_probe_test
  fi
elif [ "$RUN_PROBE_AFTER_SETUP" = "y" ]; then
  run_probe_test
fi
